chore(CI): timeout OmniOS package installation after 10 mins & avoid installing gcc13
Signed-off-by: balagrivine <balagrivine@gmail.com>

diff --git a/.github/workflows/bsd_illumos_build_test_tidesdb.yml b/.github/workflows/bsd_illumos_build_test_tidesdb.yml
--- a/.github/workflows/bsd_illumos_build_test_tidesdb.yml
+++ b/.github/workflows/bsd_illumos_build_test_tidesdb.yml
@@ -162,11 +162,12 @@ jobs:
           sync: rsync
           copyback: false
           prepare: |
+            pkg install lz4 zstd || true
             pkg set-publisher -G '*' -g https://pkg.omnios.org/r151048/extra extra.omnios || true
             for attempt in 1 2 3 4 5; do
-              timeout 600 pkg install ooce/developer/cmake lz4 zstd && break
-              echo "pkg install attempt $attempt failed or timed out, retrying in 30s..."
-              sleep 15
+              timeout 600 pkg install ooce/developer/cmake && break
+              echo "pkg install attempt $attempt failed or timed out, retrying in 60s..."
+              sleep 10
             done
           run: |
             echo "*=====================================*"
